### ISSUE TITLE
go.work file failure

### ISSUE THREAD

**Issue by gedw99** [oligot/go-mod-upgrade#50]
seems it does not like a go.work file

```sh
go-mod-upgrade
   • Workspace mode            gowork=/Users/apple/workspace/go/src/github.com/gedw99/task-ui/.src/go.work
   ⨯ upgrade failed            error=go.work:3: unknown directive: toolchain
```

```sh
go 1.19

toolchain go1.22.0

use ./task-ui

```

**Comment by oligot** [comment]
This may already be fixed in #46

Can you try again with [v0.10.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.10.0) that has just been released ?

**Comment by jherman** [comment]
I believe this problem may still exist. I have a monorepo with several packages. I attempted to upgarde one package that does not rely on any of the packages, but I get the following error:
```
   • Workspace mode            gowork=C:\repos\bitbucket.org\XXXXX\cc\go.work
   • Using directory           dir=C:\repos\bitbucket.org\XXXXX\cc\agent
   ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: bitbucket.org/XXXXX/cc/shared/pub@v0.0.0: invalid version: unknown revision shared/ion shared/pub/v0.0.0
go: bitbucket.org/XXXXX/cc/shared/pub@v0.0.0: missing go.sum entry for go.mod file; to add it:
        go mod download bitbucket.org/XXXXX/cc/shared/pub
```

However when I copy this package to an entirely new directory without a go.work, it then works: 
```
  • Using directory           dir=C:\repos\pub
? Choose which modules to update  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [ ]  cloud.google.com/go/storage          1.30.1             -> 1.41.0
  [ ]  github.com/google/uuid               1.3.0              -> 1.6.0
  [ ]  golang.org/x/net                     0.15.0             -> 0.25.0
  [ ]  golang.org/x/sys                     0.12.0             -> 0.20.0
```

Any suggestions?

**Comment by gedw99** [comment]
> This may already be fixed in #46
> 
> Can you try again with [v0.10.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.10.0) that has just been released ?

I am using the latest with go.work and it’s works fantastically

**Comment by gedw99** [comment]
> I believe this problem may still exist. I have a monorepo with several packages. I attempted to upgarde one package that does not rely on any of the packages, but I get the following error:
> 
> ```
>    • Workspace mode            gowork=C:\repos\bitbucket.org\XXXXX\cc\go.work
>    • Using directory           dir=C:\repos\bitbucket.org\XXXXX\cc\agent
>    ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: bitbucket.org/XXXXX/cc/shared/pub@v0.0.0: invalid version: unknown revision shared/ion shared/pub/v0.0.0
> go: bitbucket.org/XXXXX/cc/shared/pub@v0.0.0: missing go.sum entry for go.mod file; to add it:
>         go mod download bitbucket.org/XXXXX/cc/shared/pub
> ```
> 
> However when I copy this package to an entirely new directory without a go.work, it then works:
> 
> ```
>   • Using directory           dir=C:\repos\pub
> ? Choose which modules to update  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> > [ ]  cloud.google.com/go/storage          1.30.1             -> 1.41.0
>   [ ]  github.com/google/uuid               1.3.0              -> 1.6.0
>   [ ]  golang.org/x/net                     0.15.0             -> 0.25.0
>   [ ]  golang.org/x/sys                     0.12.0             -> 0.20.0
> ```
> 
> Any suggestions?
Are you able to provide a reproduction repo perhaps ?

**Comment by oligot** [comment]
> Are you able to provide a reproduction repo perhaps ?

Yeah, @jherman a reproduction repo would help us to find if there is a problem or not.
